sudo: false
language:
- java
before_install:
- ./src/main/bash/etcd_travis_install.sh
script:
- ./src/main/bash/etcd_travis_run.sh
- ./gradlew build -Dorg.slf4j.simpleLogger.defaultLogLevel=debug
jdk:
- oraclejdk7
env:
  global:
    - CI_DEPLOY_USERNAME=fake
    - CI_DEPLOY_PASSWORD=fake
    - CI_TRAVIS=true